/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/*
 * This is a proxy for libpurple PurpleGroup but is also used for tags
 * that aren't stored on the servers (and on libpurple's data
 * structures)
 */

[scriptable, uuid(01bbc525-fc5f-4ed1-92f0-f4f701e22fb3)]
interface purpleIPlugin: nsISupports {
  void registerSelf();
};
